---
title: "Visualization and EDA"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

```{r}
weather_df
```

Let's make a scatterplot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

I always like the dataframe first.

```{r}
ggplot_temp_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggplot_temp_scatterplot
```

Let's make this a bit fancier...

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.25) + 
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.25) + 
  geom_smooth(se = FALSE)
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_smooth(se = FALSE)
```

Show faceting

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  facet_grid(. ~ name)
```

Same as above but facet_grid different.

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  facet_grid(cols = vars(name))
```

Let's look at something else.

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Learning check: Make a plot of central park tmax v tmin only, and convert temperatures to farenheit.

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```



